jdk:
    vendor:
        name: Oracle-JDK
        version: ${java.version}
gradle:
    version: 8.7
    DSL: Kotlin
spring:
  application:
    name: ai-demo
    version: 0.0.1-SNAPSHOT
    description: DEMO project for using Mistral AI
  output:
    ansi:
      enabled: always
  config:
    import: classpath:env/Mistral.env[.properties]
  devtools:
    restart:
      enabled: true
      exclude: static/**, public/**
      additional-paths: src/test/resources/**
  ai:
    mistralai:
      api-key: ${MISTRAL_API_KEY}
      chat:
        options:
          model: mistral-small-latest
          temperature: 0.7
management:
  endpoints:
    health:
      show-details: always
      show-components: always
    web:
      exposure:
        include: "health, info, metrics, prometheus"
