jdk:
    vendor:
        name: Oracle-JDK
        version: ${java.version}
gradle:
    version: 8.7
    DSL: Kotlin
spring:
  application:
    name: ai-demo
    version: 0.0.1-SNAPSHOT
    description: DEMO project for using Mistral AI
  output:
    ansi:
      enabled: always
  config:
    import: classpath:env/Mistral.env[.properties]
  ai:
    mistralai:
      api-key: ${MISTRAL_API_KEY}
      chat:
        options:
          model: mistral-medium
          temperature: 0.7
